### ISSUE TITLE
Option to set database name during setup

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#112]
This issue is related to https://github.com/hyn/multi-tenant/issues/56

It would be great to be able to set the database name during setup. Currently the database is being named by concatenating the tenant_id and the identifier.

**Comment by luceos** [comment]
Hi, 

Once again, the SetupCommand was never meant to be used to add Tenants. It was meant for the post-installation step of the package. In order to fulfil your request what needs to be done is create a new command "TenantCommand" which allows for some regular actions, like adding, updating and deleting tenants.

I'll see whether I can push this in any time soon. My first priority for 2.x however is to rename all Tenant terminology in the code so it's not used any more. See #60 .

Also, for the sake of obscurity, let's keep the discussion in one ticket ;)

**Comment by deleugpn** [comment]
> the SetupCommand was never meant to be used to add Tenants.

Are you referring to this? 

`sudo php artisan multi-tenant:setup --customer=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=(nginx|apache|no)`

If that's not the proper way to add a new Tenant, what is? Should I manually add to the database and run the `php artisan webserver:toolbox --update-configs`? Also, if that's not the proper way to add a new Tenant, but it ends up adding one, what is the goal of the generated record?

**Comment by luceos** [comment]
The best practice to add a new Tenant is to add the objects and persist them. There is event listener that checks when a new tenant is created, which will fire the WebserverCommand to update the configuration and create the directories.

An example on how to implement adding a tenant is documented in the [readme](https://hyn.readme.io/docs/tenants#example-code-helping-you-manage-tenants).
