### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by MithrandirDK** [hyn/multi-tenant#154]
I am trying to write unit tests for models in my tenant system, but am coming up short.
My test class looks like this:

```
<?php

use App\Cluster;
use Hyn\Framework\Testing\TestCase;

class ClusterTest extends TestCase
{

    public static function setUpBeforeClass()
    {
        Cluster::create();
    }

    public function testStore()
    {
    }

    public static function tearDownAfterClass()
    {
        $clusters = Cluster::all()->get();

        $clusters->each(function ($cluster) {

            $cluster->delete();
        });
    }

}
```

It reports "Class 'Config' not found" in 

```
public static function tenantConnectionName()
    {
        return Config::get('multi-tenant.db.tenant-connection-name', 'tenant');
    }
```

Could you give some guidance as to how to write unit tests in a multi-tenant system? I don't mind setting which tenant to use manually, but I feel I lack some basic foundation to build upon.

**Comment by luceos** [comment]
First of all, writing unit tests like the ones you are attempting to write has nothing to do with my package. Second of all using setUpBeforeClass is frowned upon and will most likely not work, because Laravel uses setUp and tearDown to instantiate/setup the application before each method. The setUp method is called after the setUpBeforeClass, so the Laravel application isn't yet available.

Instead you should create your own setUp method and call the parent setUp within.

**Comment by MithrandirDK** [comment]
Well... getting a tenant database connection for unit tests has something to do with your package, I think - but ok, I will not bug you with that, then.

And yes, I don't know where I found that setUpBeforeClass and tearDownBeforeClass example - I got it working now with just setUp, tearDown and manually setting the tenant database connection in config.

**Comment by luceos** [comment]
The test you are writing is related to your own code, which uses the tenant connection, I agree. But I have no insight into your code and as such cannot help you with writing tests for them. The package by itself also tests the tenant connection, if you need examples how to write tests for them check the tests in the package.
