### ISSUE TITLE
Using incorrect database connection

### ISSUE THREAD

**Issue by bubblemedialtd** [hyn/multi-tenant#175]
I'm extending the TenantModel in my Property Model, but the DB facade is using the global database connection.

Code below:

````
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Landlord;
use Illuminate\Support\Facades\DB;

class Property extends TenantModel
{
	/**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'properties';
    //
    
     /**
     * Return all properities with adjoined landlords
     *
     * @var array()
     */
    public static function getAllProperties(){
    	$properties = DB::table('properties')
    		->join('landlords', 'landlord_property.landlord_id','=','landlords.id')
    		->join('landlord_property', 'properties.id', '=', 'landlord_property.property_id')
    		->select('properties.*','landlord_property.property_id','landlord_property.landlord_id','landlords.*')
    		->get();
    		
    	return $properties;
    }
    
}
````

**Comment by MithrandirDK** [comment]
How would you expect it to function? That the DB facade always uses the tenant connection? Or that the DB facade should know that it is being called from a class that extends TenantModel and therefore should use tenant connection?

I'm unsure where the 'incorrectness' comes from, so please elaborate.

**Comment by bubblemedialtd** [comment]
Given that the model is extending the TenantModel, I'd expect it to use the tenant's database connection, not the global connection.

If that is not the case, how do I specify to the DB facade to use the TenantModel database connection? The query builder uses the correct connection, if I were to use the following:

`Property::all();`

**Comment by MithrandirDK** [comment]
The model is extending the TenantModel - but that has nothing to do with the DB facade. It is completely de-coupled from where it is called.

The query builder uses the correct connection, because it is part of the Property class' built-in functionality, but the DB facade is called statically and has no knowledge of where you call it from.

See https://laravel.com/docs/5.3/database#using-multiple-database-connections for how to get the DB facade to use a specific connection (repeated because I edited my original reply and you may not have seen it)

**Comment by Luceos** [comment]
```
static::getConnection()-><etc>
```

This should work. It actually instantiates a Connection instance based on the connection of the current Model object.
