### ISSUE TITLE
Move Migration Scripts?

### ISSUE THREAD

**Issue by psaunders** [hyn/multi-tenant#181]
I'm just wondering, a friend and I have both run into issues with the migration scripts. I made a PR fixing one a while ago but it seems they're still getting in the way and a lot of the problems seem to be related to having them mixed in there with migration files for tenants and all those if checks.

Is there a reason that the migration scripts related to HYN aren't kept in the vendor directory and migrated by HYN (Create your own instance of Migrator.php and feed the migration files in /vendor/hyn in there). Would you like to go that direction?

**Comment by luceos** [comment]
Sounds very plausible. If you're running on v2 already feel free to send in a PR. I'm actively working on version 3 so I might pull that in as well, I separated the source for now.

**Comment by luceos** [comment]
For v3 I'm considering simply running based on path by the way.

**Comment by luceos** [comment]
Related to this, we might even consider having migrations specific for one tenant only. If that is a plausible use case the implementation of such a Migrator class could then also more easily migrate the system migrations and global tenant migrations.. Hm.. 🤔

**Comment by humbugz** [comment]
Tenant-specific migrations would be a good idea I think; it's certainly an aspect likely to come up in our project. I can see a scenario where one, or a few, tenants have an add-on feature or two that doesn't apply to the majority of sites. That's possible at the code level with routing and what not, but could also include DB requirements to support.

That actually may be better described as migration-by-feature rather than tenant. I.e. being able to create groups of migrations that can be applied to specific tenants, but not necessarily all. This way you wouldn't need to bloat unrelated tenant DB's with tables they don't need, nor would you need  multiple copies of the same migration to be applied to different tenants - you'd apply a shared set of migrations to multiple tenants as needed.

It's a thought!

**Comment by luceos** [comment]
Great idea, just not having any clue how to pursue such grouping at this point 😄

**Comment by humbugz** [comment]
Can't say I've considered the implementation details much myself as of yet! :)

As a general thought I could see something along these lines:
- Within the database folder (to keep /migrations global) a /features folder
- Inside of /features are sub folders for each set of feature related migrations. E.g. lets say we have /features/quiz with various migration files inside as you might in /migrations.
- An artisan command handles the running of these migrations, something along the lines of:
`php artisan migrate:feature --feature quiz --site somedomain.com`

That would keep site/feature specific migrations grouped separately from global migrations without having to replicate the same migration within multiple target site folders.

Obviously easier said than done! @Luceos, from your standpoint do you seen any obvious issues with the concept? There would be some fun in tracking migration application / reset / rollback between global and feature migrations...  @psaunders would something like this address the issues you're experiencing?

**Comment by luceos** [comment]
In 3.x you will be able to provide a realpath option to the migration command.

Obsoleted.
