### ISSUE TITLE
Upgrade to 5.3/5.4

### ISSUE THREAD

**Issue by insign** [hyn/multi-tenant#187]
Since it will be used for many apps, be up-to-date looks a must... LTS lseems behide in many features...

**Comment by deleugpn** [comment]
Any plans to support 5.4 soon? Any known breaking changes?

**Comment by luceos** [comment]
No immediate plans yet. Major overhaul was halted due to other responsibilities.

**Comment by luceos** [comment]
@bkintanar is putting effort on getting the compatibility done. However in version 3 of this package, which is currently in development.

**Comment by utf4** [comment]
This is great package and I am using it for many projects. It will be great if this package support Laravel 5.4.

**Comment by deleugpn** [comment]
It is indeed a great package, but given my necessity for Laravel Dusk, I decided to just keep it simple with a TenantConnector middleware and move on.

**Comment by insign** [comment]
I'm using a Middleware too...

Em 5 de mar de 2017 08:10, "Marco Aurélio Deleu" <notifications@github.com>
escreveu:

**Comment by luceos** [comment]
There has been some progress already from my side on the 3.x branch. I still cannot guarantee anything yet, trying to set it up for both 5.3, 5.4 and dev-master of framework (instead of focussing on just one).

If you want to stimulate progress on that version, feel free to buy me a [cup of coffee](https://paypal.me/luceos), make sure you add a comment mentioning this package or issue ;)

**Comment by MithrandirDK** [comment]
I have forked the 2.x repo and tested with 5.4 - to me, it looked like only a few changes and it was usable (disclaimer: I don't use the dynamic webserver configuration - only the tenancy part)

You can find it here: https://github.com/MithrandirDK/multi-tenant/tree/laravel54
It has a few extra things such as caching of HostnameRepository::findByHostname() and findByWebsiteId() and some personally necessary stuff like forcing HTTPS and setting a 'testing' connection as the one to use when in testing environment.

I have also removed the core-overriding Artisan commands since I did not use them and the line
$app->registerDeferredProvider(SeedServiceProvider::class);
caused issues with Laravel 5.4 (SeedServiceProvider no longer exists in 5.4)

You can compare here: https://github.com/hyn/multi-tenant/compare/2.x...MithrandirDK:laravel54?expand=1

**Comment by luceos** [comment]
@MithrandirDK would be great if you could send in a backward compatible PR for 2.x. Might be a bit more work, but that would help a lot of people I guess.

**Comment by luceos** [comment]
Closing this, support for 5.3, 5.4 and dev-master (5.5) is part of 3.x, which is being tested continuously using gitlab-ci with a high code coverage.
