### ISSUE TITLE
Migrations should not be published

### ISSUE THREAD

**Issue by Thijmen** [hyn/multi-tenant#307]
A few releases back, publishing migrations was introduced.
In my opinion, a developer should not be able to change the main migration because the models are relying on it.

Also, the migrations are added with 2017_01_01 in stead of the current date. 
It would be nicer to just migrate the tenancy tables with `tenancy:install` and then the user-migrations.

**Comment by TNovalis** [comment]
The way the majority of packages do it is they publish migrations, that is why I added that change, it is what most people expect when a package has migrations.

**Comment by luceos** [comment]
@tnovalis I totally understand. In fact this procedure is suggested in the documentation as well. I should have been more aware of the possible consequences of this modification, because the package has a very specific use case. We simply cannot assume that the database migrations folder belongs to the system connection as some implementations might use it for tenants or even a third connection, eg a landing page domain.
