### ISSUE TITLE
Unit testing broken

### ISSUE THREAD

**Issue by juhasev** [hyn/multi-tenant#356]
__Description__

After going from 15 to 17 unit testing is now broken.  Any unit tests that interacts with any controller will crash. After  going from 15 to 17 unit tests are now failing to error: 

Illuminate\Contracts\Container\BindingResolutionException: Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable. 

Settings during while running unit tests: 
hostname.auto-identification => false 
hostname.early-identification => false 
hostname.abort-without-identified-hostname = false 
db.default => false

---

__Information__

- hyn/multi-tenant version: 5.17
- laravel version: 5.5
- database driver and version: SQLite
- php version: 7.1

**Comment by Thijmen** [comment]
Could you please provide some more information about your unit tests, e.g. some examples?

**Comment by fletch3555** [comment]
@juhasev, since you believe the issue is related to my commit, I figured I'd chime in.  Were you running the package's unit tests, or unit tests for your own app?  I'll assume you're only referring to the package's unit tests, until you say otherwise.

The error you describe sounds like `CurrentHostname` has not yet been added to the DI container, which is done when `Environment` is instantiated (`__construct()` => `identifyHostname()` => [add singleton to container](https://github.com/hyn/multi-tenant/blob/5.x/src/Environment.php#L60)).  This tells me that either you have something misconfigured, or one of the tests is trying to get the current hostname without first instantiating an `Environment` object or ensuring early identification is enabled.  In either case, we would need more information as @Thijmen said.  A stacktrace (run phpunit in verbose mode) would be extremely helpful, but the name of the failing test would be a good start.

**Comment by juhasev** [comment]
I think we can close this issue. Really the problem here was that I was trying to use this package the way it is not intended to be used. You either configure the package to provide full "transparent" tenant switching or things start falling apart sooner or later like this hostname issue. You end up to the point where you need to manually disable tenancy or change some tenancy settings in order to do things like run php unit tests or execute artisan commands. Package does not support unit testing very well and there is no support for SQLite...

I finally just switched to full tenant detection mode (one tenant must always exist) and figured out a workaround to unit test my application which is here:

https://github.com/hyn/multi-tenant/issues/312

Things are running smoothly now. However, I do think that my work around for testing could be adopted for the package. After all you just want to unit test your application logic with one tenant only.
