### ISSUE TITLE
What's the reason behind the tenancy.json file

### ISSUE THREAD

**Issue by PiranhaGeorge** [hyn/multi-tenant#366]
Hi,

I'm just getting started with this package, but I'm finding it does pretty much everything I need :grinning:!

I am having some workflow issues though. I'm installing and running in a vagrant vm, however I tend to use artisan and composer on my host machine. Obviously, this doesn't work once installed (no database to connect to).

I'm wondering if the installation is really necessary? Assuming the following are true: 

- Installation is only used to determine if the hostname should be identified (no installation = no database)
- Installation is done through artisan
- Artisan should always default to the system connection

Rather than checking for an installation status to identify the hostname, surely it's just a case of setting the current hostname to null when running in the cli.

Happy to do a PR for this if agreed

Cheers,
George

**Comment by luceos** [comment]
The tenancy.json file is used to prevent the Environment from querying system tables that aren't there yet. Although I seem to not quite grasp your proposal, having artisan default to system will still cause issues if you ignore the tenancy.json file logic, because no tables exist..

Could you clarify a bit? Hm, are you suggesting in the Environment class to check whether we are running in cli and set the CurrentHostname resolver to return null by default? That, actually makes sense.

**Comment by PiranhaGeorge** [comment]
> The tenancy.json file is used to prevent the Environment from querying system tables that aren't there yet. 

Yes, but it seem in order to identify the current hostname, something that can't exist under a cli.

> Although I seem to not quite grasp your proposal, having artisan default to system will still cause issues if you ignore the tenancy.json file logic, because no tables exist..

But they don't necessarily need to exist.

> Could you clarify a bit? Hm, are you suggesting in the Environment class to check whether we are running in cli and set the CurrentHostname resolver to return null by default? That, actually makes sense.

That's exactly what I'm saying, but I think it removes the need for the tenancy.json.

**Comment by PiranhaGeorge** [comment]
Reading my op back, I think I made it confusing my conflating installation with the tenacny.json file.

Maybe I'm missing something, but I don't think the tenancy.json file is required if Environment doesn't try to identify the hostname under cli.

**Comment by fletch3555** [comment]
@luceos, seems this change would resolve (at least most of) your issues with my PR #365, yes?

**Comment by Thijmen** [comment]
I'd suggest not removing the tenancy.json, as some may use it to identify in their AppServiceProvider if tenancy is already installed.

**Comment by fletch3555** [comment]
I've never really been a fan of using file existence to check for status.  It's a very *nix way of doing things, but doesn't really translate to "web" well, since there's usually a better way.  *nix apps generally don't have a database to check against.

Instead, we could just do a check for the existence of the `hostnames` table on the `system` connection instead.  One extra query never hurt anyone, and it's not like anyone is going to be using this package without a database connection set up, so it's not like it's a new dependency.  OR, since this is really only used in one place, we just catch the exception that gets thrown and "return null" instead of the hostname object.

**Comment by PiranhaGeorge** [comment]
@Thijmen That's a good point, but maybe it could be deprecated in favor testing the database.

**Comment by PiranhaGeorge** [comment]
@fletch3555 beat me to it :-)

**Comment by PiranhaGeorge** [comment]
> ..we just catch the exception that gets thrown and "return null" instead of the hostname object.

This works, but I think it makes sense that Environment has some 'awareness' of if it's running in cli.
