### ISSUE TITLE
Laravel 5.6 Dependancy

### ISSUE THREAD

**Issue by itguy614** [hyn/multi-tenant#383]
Update package for Laravel 5.6 support.

**Comment by Thijmen** [comment]
It's on our roadmap, however feel free to create a PR which adds support for L5.6.

**Comment by itguy614** [comment]
Forked and working through it.

**Comment by itguy614** [comment]
Making some progress...

```
[02:16:57]$  vendor/bin/phpunit --configuration vendor/hyn/multi-tenant/phpunit.xml vendor/hyn/multi-tenant/tests/unit-tests/InstallationTest.php -vvv
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.14
Configuration: /Users/kwolf/code/packages/multi-tenant/phpunit.xml

.........                                                           9 / 9 (100%)

Time: 484 ms, Memory: 16.00MB

OK (9 tests, 20 assertions)
```

**Comment by itguy614** [comment]
Looking at the code from @Maveriks, I think he is now further along than I got to and I think his implementation is stronger than mine.  I'm going to close this in favor of the existing pull request.

**Comment by pscheminger** [comment]
Wait, what do you mean it's on your "roadmap"? If you are going to put a package out for public use you should be one step ahead of the game and make sure it's usable on future Laravel releases. Am I wrong? I have a client using your package and it completely broke because you aren't supporting Laravel 5.6. Not good man, and it's put me in a very bad situation.

**Comment by Thijmen** [comment]
@pscheminger You could've looked at our requirements (https://github.com/hyn/multi-tenant/blob/5.x/readme.md). It's not our fault it broke your app/website, as we clearly state it is only for 5.5 for now. We are busy on implementing 5.6, but as it is open source we are doing this in our free time.

However, feel free to put in a PR which supports 5.5 and 5.6, as we want to support the latest LTS of Laravel.

**Comment by luceos** [comment]
@pscheminger 

Hello Phil,

As owner of this package I'd like to take my responsibility and point out my and your obligations.

- This package is open source. You are not paying for any level of support, there's no legal contract which requires me to provide it either.
- This package has a constraint on Laravel 5.5.* not 5.6.*. Composer would object installing it on laravel 5.6 or upgrading laravel to 5.6 while this package was installed.
- If you feel so strongly about us supporting Laravel 5.6 and you have clients relying on that compatibility, feel free to support the development financially over at [patreon.com](https://patreon.com/luceos) or at [OpenCollective](https://opencollective.com/tenancy). Because we also need to make a living, support families while still trying to push out work on this package.
- I urge you to look into DTAP, development, testing, acceptance production. You would have prevented your "bad situation" by testing package compatibility before deploying it to production.

I'm terribly sorry this happened to your client. 5.6 support is happening, it will take a little time to get it into our testing procedures as well though.

**Comment by pscheminger** [comment]
Thank you for your feedback and information, it's very much appreciated!

**Comment by luceos** [comment]
@pscheminger hyn/multi-tenant 5.1.0 was tagged with compatibility to laravel 5.6; made possible by our newest sponsor @itguy614 🤗  and the contribution by @Maveriks 😍

**Comment by k33n** [comment]
@luceos thanks for the continued effort, we just contributed via open collective and will look for other ways to support the project.

**Comment by luceos** [comment]
@k33n thank you so much, your donation allows me to spend more time on development of this package 🥇 🤗
