### ISSUE TITLE
[Filesystem] Performance optimization with remote FileStorage

### ISSUE THREAD

**Issue by CodeSkills** [hyn/multi-tenant#399]
__Description__

When using this package with remote FileStorage (like S3, Minio or so), each request connects and loads the data from the remote storage, which makes the response much slower.

__Actual behavior__

Loads data from storage every request.

__Ideal behavior__

Cache the loaded data or make an option to disable loading data from storage with every single request.

__Information__

- hyn/multi-tenant version: 5.0.17
- laravel version: 5.5.13
- php version: 7.2.2

**Comment by luceos** [comment]
Can you specify what exactly is stored remotely? The tenants directory?

**Comment by luceos** [comment]
Okay so the problem is most likely related to the Filesystem adapter being created whenever the tenant is identified, on every request. This has a detrimental effect on the loading time of the page, especially in case of remote storage.

**Comment by CodeSkills** [comment]
In my scenario - I have two App servers with load balancing. I can't store anything locally, since its not the responsibility of the App server, so I made a Minio File storage server for all (by default locally stored data). So whole file storage is remote. 

As far as I know, it checks & creates the tenant folders and then loads the tenant data from it.

It is possible to disable loading tenant specific data (like routes, vendor or so), but even when disabled, it connects to the file storage every time. By guess is, that is connects and checks if the tenant directory is created or something..

**Comment by AustinMaddox** [comment]
Can anyone elaborate on this issue and offer possible workarounds?

This issue just bit us **HARD** as we launched our application live. Not even a month after launch our AWS bill skyrocketed to hundreds of dollars and we found the culprit was the charges for ~66 million requests to S3. About ~33 million were PUT, COPY, POST, or LIST requests and another ~33 million were GET requests.

What _exactly_ is the connection to the file storage on each request doing? Can someone point me to the code in the _hyn/multi-tenant_ repo that does this? We're willing to investigate and potentially submit a PR to the project if we get pointed in the right direction. I've also tried what @CodeSkills tried and disabled tenant-specific data (routes, vendor, media, etc.) but even with those disabled it connects each time.

**Comment by luceos** [comment]
I'll be adding functionality to disable tenant specific folder operations completely in 5.2; would that suffice in your use cases @AustinMaddox and @CodeSkills ?

**Comment by CodeSkills** [comment]
I hope so. Other solution would be to cache the loaded data. But that could be done later. 

Thanks for update :)

**Comment by luceos** [comment]
So the fix involves two things:

- the `ActivatesDisk` listener no longer instantiates a disk and registers it, instead it sets the `filesystems.disks.tenant` key to the specified configuration.
- the local-only logic, overrides to config, vendor etc can now be disabled.

^ -- part of 5.2

**Comment by AustinMaddox** [comment]
> I'll be adding functionality to disable tenant specific folder operations completely in 5.2; would that suffice in your use cases @AustinMaddox and @CodeSkills ?

It's been a while, but, we're now running multi-tenant version 5.2 and need to address this. In our case, we cannot set `website.disk` to `false` and disable tenancy specific folder operations completely in config/tenancy.php because we use S3 to store images uploaded by tenants. We *do not* use the overrides... things like the config, translations, vendor, etc.

Obviously our AWS bill is still very high due to all the LIST/HEAD requests. Is there anything we can do to solve this?
