### ISSUE TITLE
[Request/Proposal] Renaming Customer to Tenant

### ISSUE THREAD

**Issue by OwenMelbz** [hyn/multi-tenant#404]
I know this is a completely breaking change, however the name "Customer" is very generic, and can be a little in-descriptive, especially in certain circumstances.

For example, the system we're looking to build needs to be multi tenancy - however each tenant has a concept of a "Customer" already

What is the reasoning behind having such a generic name? and is there scope in the future of potentially renaming to allow less confusion between the 2 things.

Thanks :)

**Comment by luceos** [comment]
Hi @OwenMelbz , thank you for joining in. 

Technically [a tenant is a Website](https://laravel-tenancy.com/docs/hyn/5.x/concepts), because a website is being served from the same code base. Not a customer. A customer can have multiple websites. Nevertheless the human side of a tenant could be related to a customer, but that doesn't match up with the technical implementation.

As this has been confusing to explain in the past, I decided a while ago to remove it completely. Re-introducing this would also re-introduce the confusion. Which is not something I'd like to do. 

The successor will once again have the Tenant, but in this package this also relates to the technical implementation, not the human interpretation. As the new package will not have a Customer object shipped along, the confusion will be prevented.
