### ISSUE TITLE
force-tenant-connection-of-models fails with Laravel Spark

### ISSUE THREAD

**Issue by kylekz** [hyn/multi-tenant#499]
__Description__

Installed Laravel Spark, added its models to the `force-tenant-connection-of-models` array and they're still forcing themselves onto the system connection. May not be strictly Spark related, it's just what I'm running into issues with. Talking with luceos on Discord, we've tried:

- Debugging Model::getConnection, results in: https://i.imgur.com/2T1ketQ.png
- Using `print_debug_backtrace`, results in nothing.
- Moving `boot()` to `register()` in `Hyn\Tenancy\Providers\Tenants\EventProvider`, results in `ReflectionException (-1) Class cache does not exist`

We were thinking it may be relation related, but where the code is failing, it's accessing the Notification model and querying it directly rather than off a relation.

---

__Actual behavior__

Forces itself to the system connection where the table doesn't exist. See error log below.

__Expected behavior__

Should use the tenant connection to find the correct prefixed table.

---
__Information__

- hyn/multi-tenant version: 5.1.15
- laravel version: 5.6.24
- spark version: 6.0.10
- database driver and version: MySQL 5.7.22
- webserver software and version: nginx/1.13.12
- php version: 7.1.16

---

__tenancy.php config__

https://gist.github.com/xKairu/734a1258c87d5cd2a2909dd0e735fed1

```
LIMIT_UUID_LENGTH_32=true
TENANCY_DIRECTORY_AUTO_DELETE=true
TENANCY_DATABASE_AUTO_DELETE=true
TENANCY_DATABASE_AUTO_DELETE_USER=true
TENANCY_DATABASE_DIVISION_MODE=prefix
TENANCY_EARLY_IDENTIFICATION=true
TENANCY_DEFAULT_CONNECTION=system
```

__webserver.php config__

https://gist.github.com/xKairu/59da2d10bfcd2e7db12bb8d235067c27

---

__Error log__

https://gist.github.com/xKairu/2d2425fa7f8fcecd6a015f572621e58b

**Comment by kylekz** [comment]
Just updated to 5.2 beta and the issue still persists. Other than hardcoding changes to Spark itself, I haven't found any solution either.

**Comment by luceos** [comment]
So...

- SparkServiceProvider::register binds the contract NotificationRepository to the implementation; while binding Laravel always creates an instance (yes) of the bind in case it's a singleton
- because the binding has already taken place, the booted event being listened on by tenancy is possibly too late https://github.com/hyn/multi-tenant/blob/e7b0e3b15489d452e958dd9458dd6dc030b93253/src/Listeners/Database/OverridesConnection.php#L35

A solution would be to add the Tenancy service provider inside `config/app.php` so that it is registered before the Spark service provider (automatically) and to enable early/eager identification so that the event is being listened on.

There are alternatives to this solution I might suggest but they would require changes to the package.. I'd love to hear first whether my hunch was correct and the above solves your issue.

**Comment by kylekz** [comment]
Added tenancy to the don’t discover in composer.json, added tenancy’s provider above Spark, enabled early identification, cleared caches etc etc. Still getting the same error.

Edit: Updated stacktrace: https://gist.github.com/xKairu/231f7a0c08e1929c7d54f8f82d78069a

**Comment by luceos** [comment]
This should have been fixed, please confirm and re-open in case it still causes troubles.
