### ISSUE TITLE
Single domain multi tenant application.

### ISSUE THREAD

**Issue by dneykov** [hyn/multi-tenant#527]
I want to make admin dashboard but not separated by subdomains. Just single domain e.g example.com.
Depending on logged user I will identify the tenant. I'm not sure how can I achieve this. Should I use hostnames or no. 
I need some advices thanks.

**Comment by luceos** [comment]
Disable auto identification, then create a custom middleware which during the `handle` method will check for a user `$request->user()` and then through a custom relation with a Website will activate that Website as tenant, eg:

```php
use Closure;
use Hyn\Tenancy\Environment;

class SwitchesTenantPerUser {
	public function __construct(Environment $environment) 
	{
		$this->environment = $environment;
	}

	public function handle($request, Closure $next) 
	{
		if ($user = $request->user() && $website = $user->website) {
			$this->environment->tenant($website);
		}
	
		return $next($request);
	}
}
```

Please note this assumes hyn/multi-tenant 5.2-beta!

**Comment by dneykov** [comment]
@luceos Thanks.
Does this means that I don't have to create hostname and customer? Actually the users will identify the tenant.

**Comment by luceos** [comment]
Yes, as long as you relate a Website object to a User; you could potentially have the User object implement the Website contract then the tenant would be the User and you would not even need the Website model of this package. You can replace tenancy models inside the `tenancy.php` configuration file 👍

**Comment by Nowi5** [comment]
I think this only works when one user works on one tenant, what are you doing if the same user (same e-mail) has accounts on multiple tenants? I think about to have one tenant like admin. The user model base on system connection so the core user table is shared across all tenants and user can have 1:n tenants.
If one user is admin of multiple tenants he can see all his tenants in the admin center and he can create new one. My tenants belong to one account, so I need to think about a good selection for user which belong to the current tenant or to the tenants across the account. 
Due to that, the user name, email and password is the same across all tenants. User profile data etc are in a separate model. Does that makes sense?

**Comment by luceos** [comment]
@Nowi5 you can create a dropdown like (or landing page with tenants listed) for the user to choose from, then when user clicks that before redirecting set a cookie that sets the tenant preference. Hope that makes sense.

**Comment by BKirev** [comment]
So far I made this:
-in user model(User.php):
```php
class User extends Authenticatable implements Website
```
_Website is use Hyn\Tenancy\Contracts\Website_
and
```php
public function hostnames(): HasMany
    {
        return $this->hasMany(config('tenancy.models.hostname'));
    }
```
But it's still related to hostnames, as far as I understand?
What I want is when a new user registers in the system, it's automatically added and identified as a tenant.
The rest of the users that will be added to him will be via invite link, for example and must be attached to him.
Should I add website_id as a field into the tenant's user table?
Anything else that I should do to make it work with user instead of hostname?

**Comment by luceos** [comment]
First off, although the flexibility exists to replace the model, using a User model was never tested; as such you're moving into uncharted territory ..

What you would need to do is use the `Environment::tenant` method to force set a specific tenant, in your case User and hope the code won't break. If it does I'd love to hear about it. Make sure your user has a `uuid` property, you can use an accessor for this.

**Comment by BKirev** [comment]
Can I not replace the model then? Maybe just create a relation between user and website instead of hostname and website?

**Comment by luceos** [comment]
That is possible too 🤔 Why overcomplicate it if you don't have to 🤷‍♂️

**Comment by BKirev** [comment]
Any directions?
Should I add `website_id` in the users table? Am I going to need any modification in the package itself?

**Comment by luceos** [comment]
Not at all; create an additional migration (or use the published one from the package). You can choose for yourself whether you need a relation back from Website to User; in that case you might need to extend the Website model..
