### ISSUE TITLE
[5.2] Route in web.php is taking precedence, even with the override config enabled

### ISSUE THREAD

**Issue by bkintanar** [hyn/multi-tenant#532]
`'tenancy.routes.replace-global' => true,`.

Create `routes/tenants.php`

Create a route that has a similar route signature to one of the routes found in `routes/web.php`

Try accessing the said route, it triggers the web.php route instead of the one found in `routes/tenants.php`

Now try removing the one found in the `routes/web.php`. now it triggers the route in tenants.php.

Thanks to @fletch3555 for reporting this in Discord.

**Comment by luceos** [comment]
```
    /**
     * Global tenant specific routes.
     * Making it easier to distinguish between landing and tenant routing.
     *
     * @info only works with `tenancy.hostname.auto-identification`.
     */
```

Is that taken into consideration?

**Comment by luceos** [comment]
```
    /**
     * Global tenant specific routes.
     * Making it easier to distinguish between landing and tenant routing.
     *
     * @info only works with `tenancy.hostname.auto-identification`.
     */
```

Is that taken into consideration?

**Comment by fletch3555** [comment]
Yes, auto-identification was enabled.  I added `dump()` statements in all code branches of the RouteProvider code, and it definitely got in there.  I suspect the Hyn RouteProvider I being booted before the App RouteServiceProvider, so its being overridden.

**Comment by fletch3555** [comment]
Looks to be an issue with load-order of service providers.  After disabling auto-discovery of `TenancyProvider` then manually adding it or the provider array in `app.php` AFTER `RouteServiceProvider`, I was able to get it to load the correct route.  I also added `dump()` statements to the `map()` method of both route providers to see which is loading first.  When Hyn loads after App, it loads the tenants.php route, otherwise it loads the web.php one.

![image](https://user-images.githubusercontent.com/1387843/42298293-2534a064-7fd3-11e8-9803-cacc789df503.png)

![image](https://user-images.githubusercontent.com/1387843/42298457-f5c452d8-7fd3-11e8-8236-f60857da3536.png)

**Comment by endrureza** [comment]
i got this issue too. Is there any solution yet?

**Comment by andranikbadalyan** [comment]
Same here, just create a fallback tenant until this gets resolved.

**Comment by andranikbadalyan** [comment]
The same issue persists when trying to override through tenant routes.php
