### ISSUE TITLE
Allow APP_KEY rotation

### ISSUE THREAD

**Issue by luceos** [hyn/multi-tenant#574]
By @bkintanar ;)

Relates to https://t.co/XdhgIkbu0v

**Comment by mintunitish** [comment]
There should be some mechanism that changes the APP_KEY automatically in some intervals.

**Comment by luceos** [comment]
I think that having key rotation is very expensive with many tenants. In addition there are so many risks involved; eg jobs/crons/pages not loading due to the credentials being invalid. Something like this is best run during a maintenance window on larger platforms.

My suggestion is to write a `tenancy:key:rotate` command that will allow the key to be regenerated, and stored only after all tenant database user passwords have been updated. Something like this could be done faster by forking several processes, which in turn might run into concurrent connections issues with the system connection...

**Comment by bkintanar** [comment]
I'll try to have a whack at it.

**Comment by fletch3555** [comment]
This seems like such a one-off case... The issue is "resolved" by laravel disabling serialization.  The only reason to change keys is if you know it's been compromised.

Can we simply provide a method that accepts both old and new keys and handles it.  Then let the user create the command if that's how they want to do it, perhaps with an example in the docs.

**Comment by mintunitish** [comment]
Agree with the idea of providing a command or some sort of method to do that. However it's being fixed in Laravel v5.6.30 so that's done!

**Comment by luceos** [comment]
@mintunitish link?

**Comment by drbyte** [comment]
I'm pleased to see @luceos taking this seriously. Adding `tenancy:key:rotate` or equivalent is a great idea.

I disagree with one of the comments above:
> The only reason to change keys is if you know it's been compromised.

This Laravel 5.6.30 patch due to a discovered risk is a perfect example of a reason to rotate keys, whether compromised or not.

While I realize many of us here aren't intending to submit our apps for PA DSS or PCI DSS certification, implementing their standards results in more secure applications. Secure coding practices should start at the beginning, not as an afterthought.

I also realize that APP_KEY in Laravel isn't a complete representation of a full on cryptographic key management strategy. 

Nevertheless, if one has never heard about this stuff, it's worth the 8 minutes to read the cheat-sheet summaries linked below.

OWASP points out that the PCI standards require at least annual rotation of cryptographic keys, plus also whenever a risk/threat of compromise is encountered:

> 3.6.4 Periodic cryptographic key changes
The PCI DSS standard mandates that keys used for encryption must be rotated at least annually. The key rotation process must remove an old key from the encryption/decryption process and replace it with a new key. All new data entering the system must encrypted with the new key.

Refs:
https://www.owasp.org/index.php/Cryptographic_Storage_Cheat_Sheet
https://www.owasp.org/index.php/Key_Management_Cheat_Sheet

**Comment by fletch3555** [comment]
@drbyte, I think you've confused my comment and inadvertently argued the same point.

That Laravel patch has been announced as exactly what my comment stated.  It's only needed if your key has been compromised.  However, there are many ways it could've been compromised, including it being known by former employees, regardless of malicious intent.

All my comment suggested is that this package doesn't need a command do to the work.  Instead, it can provide that functionality in a service method (or similar) and allow those using our package to decide how they want to handle it (i.e. via a command).

As you so aptly stated, not everyone needs to submit for DSS certification, and not every site requires strict compliance with PCI standards (completely depends on WHAT information is being stored).  Since this isn't something everyone needs, we shouldn't provide a tool to do it for them.  Instead, we should provide an API for them to use in their own tool.

**Comment by drbyte** [comment]
@fletch3555 yes, it appears we are indeed saying the same thing. 
While key-rotation isn't urgent if there's not been any (known) compromise, it should still be something that's made possible, and if this package depends on keys associated with its stored data then it should provide a means of rotating them in a way that maintains the integrity of the data managed by the package.

Thumbs-up to your well-stated point:
> we should provide an API for them to use in their own tool

**Comment by luceos** [comment]
see #739
