### ISSUE TITLE
Incopatibility with Laravel/Passport

### ISSUE THREAD

**Issue by 4dri-wtf** [hyn/multi-tenant#611]
__Description__

Some models in the use tenant connection array in the config still use the system connection.

__Actual behavior__

uses the system connection

__Expected behavior__

use the tenant connection

---
__Information__

- hyn/multi-tenant version: 5.2
- laravel version: 5.6
- database driver and version: MariaDB
- webserver software and version: Apache2 
- php version: 7.1

---
Actually I made a repo with a step by step to reproduce and a dirty workaround. 
https://github.com/4dri-wtf/TenacyPassportPOC

```

**Comment by johannesschobel** [comment]
can you try this tutorial here? https://medium.com/@sadnub/hyn-tenancy-5-2-and-laravel-passport-a0d11c5a08eb

**Comment by 4dri-wtf** [comment]
@johannesschobel this works but since it forces tenant's conncetion by middleware in the whole app it does not not solve the issue. Actually I'm using a similar workaround, you can see it in my repo.

The issue is that the models in the tenancy config array should use tenants connection and it's not working with the models in Passport package.

**Comment by johannesschobel** [comment]
Not sure though, if i understand the issue correctly.. But in your repository you have 2 `User` models (in different namespaces!) that both link to the same database table (in different connections) - not sure if this works in general!

**Comment by 4dri-wtf** [comment]
the multi-tenant config allows to set some models to work with a especific connection:

````
 /**
         * Define a list of classes that you wish to force onto the tenant or system connection.
         * The connection will be forced when the Model has booted.
         *
         * @info Useful for overriding the connection of third party packages.
         */
        'force-tenant-connection-of-models' => [
            //App\User::class,
            Laravel\Passport\AuthCode::class,
            Laravel\Passport\Client::class,
            Laravel\Passport\PersonalAccessClient::class,
            Laravel\Passport\Token::class,
````

It isn't workin for passport models.

also, the traits in both models works flawlessly

**Comment by johannesschobel** [comment]
ok, and adding these models to the `force-tenant-connection-of-models` does not work, right?
in other words - the `Passport` models are not forced to the `Tenant` connection?

**Comment by 4dri-wtf** [comment]
exactly

**Comment by bkintanar** [comment]
I have encountered this as well. I've already informed @luceos. We'll have to wait when he gets back from his vacation.

**Comment by johannesschobel** [comment]
ah, ok.. now i get it.. 

A quite "dirty hack" would be to just "wrap" the required classes in your own and apply the respective Trait there.. and then switch implementations.. but i am not sure, if Passport would allow for such changes of the implementation..

**Comment by luceos** [comment]
Have you tried putting the TenancyProvider before the PassportProvider in your app.php?

**Comment by 4dri-wtf** [comment]
Just did. Same behaviour. I didn't need to have them in the conf file. I guess composer was doing the job for me. Any chances that this is causing the trouble?

**Comment by johannesschobel** [comment]
i guess, if you `autoload` service-provider, laravel registers them in whatever order.. so you don't have control over the time, a SP is loaded..

that is - amongst others - the reason, i really (and i mean, *really*) f"§$%"cking **hate** autoloading of laravel..

Can you try to `disable autloading` and manually registering the components in the `app.php` config file in the order you want them? i.e., first the `TenancyProvider` and then the `PassportProvider`?

**Comment by bkintanar** [comment]
looks like laravel is auto loading them in alphabetical order. that means
hyn is being loaded before any of the 1st party laravel packages. i.e.
passport


--
Bertrand Kintanarbertrand.kintanar@gmail.com

On Sep 17, 2018 at 15:49, <Johannes Schobel <notifications@github.com>>
wrote:

i guess, if you autoload service-provider, laravel registers them in
whatever order.. so you don't have control over the time, a SP is loaded..

that is - amongst others - the reason, i really (and i mean, *really*)
f"§$%"cking *hate* autoloading of laravel..

Can you try to disable autloading and manually registering the components
in the app.php config file in the order you want them? i.e., first the
TenancyProvider and then the PassportProvider?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/hyn/multi-tenant/issues/611#issuecomment-421918091>,
or mute
the thread

**Comment by 4dri-wtf** [comment]
So, no point in disabling the autoloading?

**Comment by johannesschobel** [comment]
@bkintanar yeah, that could be.. But autoloading messes up with packages that depend on a specific "order" (e.g., a middleware MUST be applied before another one)..
I really don't get the point why laravel introduced this "feature" - because it saves you about 30 seconds of time - but causes so much troubles afterwards.. I don't think, this was a good idea at all..

Nevermind, back to the actual issue;:
I would try to disable autoloading and manually registering the services in the order you need @4dri-wtf .. I noticed once, that autoloading happens **way earlier** in the laravel stack than the manual registering happended before.. So this may be an additional problem (especially, if SP read configuration files - they may read from `/vendor/xxx` instead of `/config` folder...

**Comment by fletch3555** [comment]
Laravel's auto-discovery functionality discovers package service providers and adds them to a list, then gets the list from config/app.php and appends that to the "discovered" list.  It then sorts it so packages beginning with "Illuminate" are loaded first, and the rest remain in the same order they were loaded (auto-discovered first, then config file).

**Comment by rvetrsek** [comment]
Is there any solution to this issue jet? I just reached the same problem and I'm really in a hurry to get this working...

**Comment by bkintanar** [comment]
Try adding this to your AppServiceProvider's `boot()` method:

```php
$env = app(Environment::class);

if ($fqdn = optional($env->hostname())->fqdn) {
    config(['database.default' => 'tenant']);
}
```

**Comment by rvetrsek** [comment]
Wow thank you, it works great! If I'm not mistaken, this also defeats the purpose of having the EnforceTenancy middleware? If it does it is even better because it applies the same effect but does it automatically.

**Comment by luceos** [comment]
@obsessen yes it does, great snippet @bkintanar 👍 Can we pr this to a sane place in the docs (faq or connection page?)

**Comment by bkintanar** [comment]
Closing this now since docs have been updated.

Link to docs: https://laravel-tenancy.com/docs/hyn/5.3/connections#forcing-the-connection
