### ISSUE TITLE
Hostname not identified when testing with Laravel Dusk

### ISSUE THREAD

**Issue by maelga** [hyn/multi-tenant#684]
__Description__

The hostname is not identified when testing with Laravel Dusk.

For browser testing, I have created a 'testing' tenant, available at http://testing.mydomain.test. When browsing "manually" through the app in Chrome, I can log in, create and retrieve records to/from the tenant db, etc... So the app works fine.

Now, when I implement Laravel Dusk, this basic test passes on http://testing.mydomain.test/test
```
$this->browse(function (Browser $browser) {
  $browser->visit('/test')
    ->assertSee('This is my test page');
  });
```
However getting the hostname on that page, $hostname returns null:

```
 $this->browse(function (Browser $browser) {
  $browser->visit('/test')
    ->assertSee('This is my test page');
  });

  $hostname = app(\Hyn\Tenancy\Environment::class)->hostname();
  dd($hostname); //returns null
```
My understanding is that the hostname should have been identified through the fqdn in the url: http://testing.mydomain.test/test. However, the above test shows that although the hostname is correctly identified when "manually" browsing Chrome, it is not identified when using Dusk.

I have a subsequent test pointing to http://testing.mydomain.test/login that requires a DB connection and it fails: "_InvalidArgumentException: Database [tenant] not configured._". It seems to relate to the same issue as above, the tenant/hostname is not identified, so the tenant DB connection does not exist.
```
        $this->browse(function (Browser $browser) {
            $browser->visit('/login')
                    ->assertSee('Sign in');
        });

        $user = factory(User::class)->create([
            'email' => 'taylor@laravel.com',
            'full_name' => 'Testing Man',
            'password' => 'secret',
        ]);  // User is not created: "Database [tenant] not configured"

        $this->browse(function ($browser) use ($user) {
            $browser->visit('/login')
                ->type('email', $user->email)
                ->type('password', 'secret')
                ->press('Login')
                ->assertPathIs('/dashboard');
        });        
```

---
__Expected behavior__

I can identify the tenant manually in every tests, like so:
```
        $environment = $this->app->make(\Hyn\Tenancy\Environment::class);
        $website = Website::find(1);
        $environment->tenant($website);
```
My 'testing' tenant having the id = 1

But, should the hostname/tenant have been already identified through the url in the first place?

---
__Information__

- hyn/multi-tenant version: 5.3.1
- laravel version: 5.7.13
- database driver and version: mysql 5.7.23
- webserver software and version: nginx 
- php version: 7.2.9

---

**Comment by fletch3555** [comment]
This looks like a misunderstanding of context.  Your tests are functioning as the client/browser, not the server.  So `app(\Hyn\Tenancy\Environment::class)->hostname()` wouldn't find anything.  It's been quite a while since I've gone diving into the inner workings of Dusk, though, so let's see what others say.

**Comment by luceos** [comment]
@fletch3555 is onto something. 

The point of Dusk is that it listens to a specific address/port combination. In order to test different tenants or a tenant/master set up you would have to start the dusk driver multiple times with different hostnames to resolve to. I think per default it uses http://127.0.0.1:8000, so hitting dusk with `/test` will resolve to `http://127.0.0.1:8000/test`.

You should be able to configure Dusk to use the host of whichever tenant you want tested, but you'll need to re-instantiate it whenever you need another host. For inspiration: https://laravel.com/docs/5.7/dusk#using-other-browsers

**Comment by maelga** [comment]
Thanks for your feedback. I have spent a couple of hours today trying to fix this, but without success.
Would you have any config files to share? Adding documentation for testing multi-tenant with Dusk would be great.

**Comment by luceos** [comment]
There are none and my knowledge of Dusk is pretty limited so offering any advice would be mere suggestion instead.
