### ISSUE TITLE
Update ssl listener

### ISSUE THREAD

**Issue by ayman-elmalah** [hyn/multi-tenant#759]
__Description of your feature__
I need to update this file
hyn\multi-tenant\assets\generators\webserver\nginx\blocks
if host is https update listen to be 443 instead of 80
..

---

__Proposed behavior__

I have website with ssl but it listen in nginx to port 80

..

__Current behavior__

listen to 443
..

---
__Information__

- hyn/multi-tenant version:
- laravel version:

**Comment by Plytas** [comment]
Hello you can create a vhost view somewhere in your resources and then specify it in `webserver.php` config: https://github.com/hyn/multi-tenant/blob/5.x/assets/configs/webserver.php#L138-L141

**Comment by luceos** [comment]
Ports are configurable from webserver.php we do need to drop further references to ssl as in that configuration.

**Comment by ayman-elmalah** [comment]
But i configure ssl, and it listen in template for 80 not 443

**Comment by ArlonAntonius** [comment]
Hi @ayman-elmalah,
Then you edit the template provided by us so it fits your situation.
Template can be found at: https://github.com/hyn/multi-tenant/blob/5.x/assets/generators/webserver/nginx/blocks/server.blade.php

Are you sure you aren't mistaking this with the actual Nginx configuration of your server instead of having to do with the package's automatic vhosts?

**Comment by ayman-elmalah** [comment]
yes i already did it, but i just ask for feature to be in the package

**Comment by luceos** [comment]
The https port in the webserver.php file is unused, that value is no longer implemented. You can still modify the http port so that the configuration generated is for https. Make sure to set up the redirection from http to https then.

---

This will not be a feature in this package. SSL used to be part of this package in a non-functional way. With the introduction of Let's encrypt the ability for the binary to take care of the certificates was sufficient to remove the logic in this package.
