### ISSUE TITLE
Breaking changes with DefaultPasswordGenerator class

### ISSUE THREAD

**Issue by diegomagikal** [hyn/multi-tenant#763]
After upgrade laravel 5.7 to 5.8 and hyn/multi-tenant from v5.3 to 5.4, all mysql users in my app are receiving the error "Access denied for user...".

After 2+ hours searching the code, I can see that it has a breaking change with `key` var in `tenancy.php` and `generate` method of `DefaultPasswordGenerator`.

This code in `DefaultPasswordGenerator` assumes that `$key` can be `null`:

```
$key = $this->app['config']->get('tenancy.key');

// Backward compatibility
        if ($key === null) {
            return md5(sprintf(
                '%s.%d',
                $this->app['config']->get('app.key'),
                $website->id
            ));
        }

        return md5(sprintf(
            '%d.%s.%s.%s',
            $website->id,
            $website->uuid,
            $website->created_at,
            $key
        ));
```
But `$key` is always filled (with `APP_KEY` value), even if `env('TENANCY_KEY', env('APP_KEY')),` in `tenancy.php` is missing. The only way I found to run without changing the vendor files was changing 
`'key' => env('TENANCY_KEY', env('APP_KEY')),`
to
`'key' => env('TENANCY_KEY', NULL),`

So, I would like to suggest this change to `tenancy.php` file...

**Comment by luceos** [comment]
Hello Diego,

Thank you for opening this issue. You are correct that this change in the DefaultPasswordGenerator will break existing installations. We are fully aware that this is the case, as such the version was bumped to 5.4 instead of tagging a patch version. Inside the upgrade guide of the documentation we clearly elaborate on this change:

![image](https://user-images.githubusercontent.com/504687/54853528-6d3bac00-4cf0-11e9-863c-6f1f5ac5cd5b.png)

For the full list of backward breaking changes I recommend reading the upgrade guide: https://laravel-tenancy.com/docs/hyn/5.4/upgrade-from-5.3#backward-breaking-changes

Once again thank you for reaching out, at this point we see no reason to change the implementation based on your feedback.
