### ISSUE TITLE
Performance Improvements Tutorial - Integration with Swoole 

### ISSUE THREAD

**Issue by lakshmaji** [hyn/multi-tenant#765]
__Description of your feature__

Swoole integration tutorial need (https://github.com/swooletw/laravel-swoole)

---
__Information__

- hyn/multi-tenant version: 5.x
- laravel version: 5.x

**Comment by ArlonAntonius** [comment]
Hi there,

Personally, I don't think we need to provide a tutorial related to this.
Laravel Swoole is simply a package to make Laravel use the Swoole extension, I don't think there's anything you need to do with this package in order to make that work accordingly.

However, it's a package I have not used with our package and if you want to document a tutorial for it, feel free.
