### ISSUE TITLE
foreign key between tenant and system db in migration is not possibile

### ISSUE THREAD

**Issue by nulele** [hyn/multi-tenant#807]
__Description__

I'd like to have common lists (such as cities, countries, groups, vat_codes...) in system db and have a foreign key with them in tenants db tables.

`Schema::table('guests', function (Blueprint $table) {
            $table->foreign('city_id')->references('id')->on('system.cities');
        })`

When I run the migration command, get the below error.

---

__Actual behavior__
`SQLSTATE[42000]: Syntax error or access violation: 1142 REFERENCES command denied to user '85bf77ef76b04cfbb67362781730ccd4
'@'localhost' for table 'system.cities'`

__Expected behavior__

I know this is expected due to user privileges (the tenant db user cannot access the system db)... Is there a way to bypass this error? Thanks

---
__Information__

- hyn/multi-tenant version: 5.4
- laravel version: 5.8
- database driver and version: mysql 5.7
- webserver software and version: nginx 1.11.1
- php version: 7.2

---

__tenancy.php config__

```php
'auto-create-tenant-database' => true,
'auto-create-tenant-database-user' => true,
'tenant-database-user-privileges' => null,
```

**Comment by luceos** [comment]
Looks like your tenant user isn't allowed to create a foreign key to the system database. Which.. actually makes a lot of sense. If you still want this, you might need to give the tenant database user additional privileges either through the config key or through an event listener..

**Comment by isecchin** [comment]
Hi @nulele, I had a similar use case and thought I could share with you what I did to solve it (based on other issues and the documentation), but it is basically what @luceos suggested.

I just created a new listener, let's say `GrantPrivileges`, to listen to the creation of new databases by the Hyn Tenancy and grant the necessary permissions to the new user.

So, you'd have, for example:

**App\Providers\EventServiceProvider**
```php
class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        \Hyn\Tenancy\Events\Database\Created::class => [
            \App\Listeners\GrantPrivileges::class,
        ],
    ];
}
```

**App\Listeners\GrantPrivileges**
```php
class GrantPrivileges
{
    /**
     * The tables which the grant privileges
     * will be assigned to.
     *
     * @var array
     */
    protected $tables = [
        'cities',
        'countries',
        'states',
    ];

    /**
     * Handle the event.
     *
     * @param \Hyn\Tenancy\Events\Database\Created $event
     *
     * @return void
     */
    public function handle(Created $event)
    {
        $config = $event->config;
        $database = config('database.connections.system.database');

        foreach ($this->tables as $table) {
            DB::statement(
                "GRANT REFERENCES ON `{$database}`.`{$table}` TO `{$config['username']}`@'{$config['host']}' IDENTIFIED BY '{$config['password']}'"
            );
        }
    }
}
```

The above query is for MySQL/MariaDB, but if you use another driver, it's just a matter of adjusting it. So what I do here is just add the tables that I need to reference on the system's DB from the tenant's one to the `$tables` array attribute, and whenever a new database is created, the listener executes the GRANT to each of the tables defined and you can create the relationship on your migration files.

And just an extra tip here, on my migration files I don't like to explicitly say that the name of the system connection is actually `system` (because that might not be true), so I request the database name, for example:

```php
use Illuminate\Database\Query\Expression;

Schema::table('guests', function (Blueprint $table) {
    $systemDB = DB::connection('system')->getDatabaseName();
    
    $table->increments('id');
    $table->unsignedInteger('city_id');
    $table->foreign('city_id')->references('id')->on(new Expression($systemDB . 'cities'));
});
```

**Comment by nulele** [comment]
Hey, wow! I'll give it a try, thank you @isecchin!

**Comment by luceos** [comment]
Thank you very much @isecchin very kind of you to share this 👍

**Comment by Samuel-Webster** [comment]
Thanks @isecchin. 

A couple of things that I got stuck with that may help others.

**App\Listeners\GrantPrivileges**

```
Add>> use DB;
Change>> public function handle(\Hyn\Tenancy\Events\Database\Created $event)
```
