### ISSUE TITLE
General error: 1348 Column 'Password' is not updatable

### ISSUE THREAD

**Issue by kamilkozak** [hyn/multi-tenant#826]
__Description__

As described on the website:
https://mariadb.com/kb/en/library/mysqlglobal_priv-table/
"The mysql.global_priv table was introduced in MariaDB 10.4.1 to replace the mysql.user table."

Because of that I get an error "General error: 1348 Column 'Password' is not updatable" when I want to use the command tenancy: key:update

---

__Information__

- hyn/multi-tenant version: 5.4
- laravel version: 5.8
- database driver and version: mariadb 10.4.6
- php version: 7.3

---

__Error log__

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000]: General error: 1348 Column 'Password' is not updatable")
      /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119

  2   PDOException::("SQLSTATE[HY000]: General error: 1348 Column 'Password' is not updatable")
      /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

```

**Comment by drbyte** [comment]
This code needs updating, to be compatible with MariaDB 10.4:
https://github.com/tenancy/multi-tenant/blob/963987bd90266b3f7d2d0e9af35a97d0d346f8be/src/Generators/Webserver/Database/Drivers/MariaDB.php#L115

**Comment by drbyte** [comment]
Seems to be resolved by reverting the platform-checking code added in https://github.com/tenancy/multi-tenant/commit/44858ed28f9a1dac3718ea6863c79f897c464999#diff-e51e809604145f74d16f6f072f6f9976

**Comment by fletch3555** [comment]
Good find @drbyte.  I'm curious what MariaDB used to do differently that made `ALTER USER` not work.  Assuming that works, I'm glad to hear they updated it to make it work with the new user/auth scheme they're following.

**Comment by drbyte** [comment]
I honestly don't know what @luceos was specifically attempting to work-around there.

I do know that MariaDB specifically no longer allows manipulating the underlying tables for password stuff starting since 10.4 https://mariadb.org/authentication-in-mariadb-10-4/ ... preferring to avoid passwords altogether for greater security. While making some devops stuff simpler it also makes scripting across versions more difficult particularly for backward compatibility.
