### ISSUE TITLE
configuration of webserver.php to work under window

### ISSUE THREAD

**Issue by ASanchezT85** [hyn/multi-tenant#827]
Greetings, I hope you can explain myself well, my English is not very good.

I am presented with the following problems, I have followed the tutorial on a verbatim basis, at the time of creating a tenant, this ne the database is created, both the hostname, and the website, the problem occurs when I redirect to the page of the tenant (tenant.tenancy.dev), the domain is not registered.

Following the answer questions here, I realized that I must configure my config / webserver.php file, enabling apache2, so that the vhost is created in the storage, and configuring my http.config file to be included ( IncludeOptional), so far so good, the problem arises at the time of creation I get the following error: "the command" apache2ctl -t! failed. "

![errpr tenancy 1](https://user-images.githubusercontent.com/10146441/62101827-cb5f3980-b264-11e9-90f8-506be30d8508.png)

In the images you can better observe the error that throws me.

I also note that the file created in storage / app / tenancy / webserver / apache2 tells me that: No hostnames found.

I have been researching for a while but I cannot find information on the subject, I have seen several comments that work for Linux without problems, I do not get it to work I ask for wisdom please.

![errpr tenancy 2](https://user-images.githubusercontent.com/10146441/62101828-cbf7d000-b264-11e9-85f9-5a1e7fe664e9.png)
![errpr tenancy 3](https://user-images.githubusercontent.com/10146441/62101830-cbf7d000-b264-11e9-8e57-c073f4c03621.png)
![errpr tenancy 4](https://user-images.githubusercontent.com/10146441/62101831-cbf7d000-b264-11e9-931c-b75dc3bddfe8.png)
![errpr tenancy 5](https://user-images.githubusercontent.com/10146441/62101832-cbf7d000-b264-11e9-93db-c064a187f79a.png)

**Comment by ArlonAntonius** [comment]
Hi @ASanchezT85,

A few small things before hand:
- We have bug reports templates, those are not optional, they are mandatory.
- When errors appear in languages other than English, please translate them so everyone understands what is happening and can get all the info
- Keep in mind that the source of the project is open, you can freely browse it and find out what's exactly happening.

### Networking
I can see you're using Windows with Laragon, Laragon doesn't provide a CLI for Apache or Nginx as far as I'm aware. So that command running probably won't work like that.

I'd recommend you to do some reading on networking on an article by one of our own members.
https://medium.com/@fletch3555/networking-your-multi-tenant-app-24a340310883

For Windows you'll probably end up adjusting the vhosts every time you create a tenant.

### No Hostnames Found
With a simple search in Github for this term, you'll find pieces in the code that show this error. https://github.com/tenancy/multi-tenant/blob/1380789375bb3eb75dbb4f951a44ec1876e5b5ee/assets/generators/webserver/apache/vhost.blade.php. It simply happens when no hostnames are assigned when creating the website.

You can take a more detailed look at the code if you want and figure out when and how the configuration gets made, but there's not much detailed help I can give without seeing the exact code you use for creating the tenant.

Here's the class responsible for creating and updating the configs https://github.com/tenancy/multi-tenant/blob/1380789375bb3eb75dbb4f951a44ec1876e5b5ee/src/Listeners/Servant.php.
