### ISSUE TITLE
File not unacceptable into the collection named avatar of the model app\user 

### ISSUE THREAD

**Issue by ogunsegun** [hyn/multi-tenant#868]
Spatie\medialibrary\exceptions\filecannotbeadded\fileunacceptableforcollection
__Description__
Have put public function registeredmediacollection()
For the type of file I what to upload but am getting error after which I use handler.php for the error but am still getting the same error 
..

---

__Actual behavior__
Error: the file with properties name:pdf size 24600 mime application was not accepted into the collection name avatar of model app\user with id 1

**Comment by Plytas** [comment]
Closing as this doesn't seem to be related to this package. Your best bet would be to open an issue on [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary) repo.

If you believe that this issue is related to this package feel free to reopen or create a new issue and provide a stack trace.
